# Generated by Django 5.0.6 on 2024-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Player_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Player_Name', models.CharField(max_length=100)),
                ('Player_Picture', models.ImageField(blank=True, null=True, upload_to='player_pictures/')),
                ('Default_Player', models.BooleanField(default=False)),
                ('Player_Chips', models.IntegerField(default=0)),
            ],
        ),
    ]
