# Generated by Django 5.0.6 on 2024-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JT_poker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('Bot_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Bot_Name', models.CharField(max_length=100)),
                ('Bot_Picture', models.ImageField(blank=True, null=True, upload_to='bot_pictures/')),
                ('Bot_Chips', models.IntegerField(default=0)),
                ('Bot_Rank', models.IntegerField()),
                ('Bot_Unlocked', models.BooleanField(default=False)),
            ],
        ),
    ]
